package com.vocabtrainer.sentences;

import java.util.List;
import java.util.Map;

import com.vocabtrainer.progress.Ctx;
import com.vocabtrainer.progress.ProgressRepository;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.ResourceAccessException;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.core.JacksonException;
import tools.jackson.databind.json.JsonMapper;

/**
 * Example sentences shown with a card. Each word's sentence is generated by
 * Gemini once and then served from Firestore for every device. The Gemini key
 * comes from the page with the request (X-Gemini-Key) and is never stored.
 */
@RestController
@RequestMapping("/api/sentences")
public class SentenceController {

    static final String MODEL = "gemini-3.6-flash"; // one-line switch if Google retires it
    private static final Map<String, String> CAT_LABEL = Map.of(
            "der", "der", "die", "die", "das", "das", "adj", "adj.", "verb", "verb", "sep", "trenn.", "func", "func.",
            "phrase", "phrase");

    private final ProgressRepository repo;
    private final JsonMapper json;
    private final RestClient http = RestClient.create();

    public SentenceController(ProgressRepository repo, JsonMapper json) {
        this.repo = repo;
        this.json = json;
    }

    /** The saved sentence for a word, or 404 if there isn't one yet. */
    @GetMapping
    public ResponseEntity<Map<String, Object>> get(Ctx ctx, @RequestParam String word) {
        requireWord(word);
        Map<String, Object> s = repo.sentence(ctx.token(), word);
        return s == null ? ResponseEntity.notFound().build() : ResponseEntity.ok(Map.of("de", s.get("de"), "en", s.getOrDefault("en", "")));
    }

    public record GenerateRequest(String de, String en, String cat) {
    }

    /** Saved sentence if there is one; otherwise generate with Gemini, save, and return it ({needsKey} without a key). */
    @PostMapping("/generate")
    public Map<String, Object> generate(Ctx ctx, @RequestHeader(name = "X-Gemini-Key", required = false) String key,
                                        @RequestBody GenerateRequest req) {
        requireWord(req.de());
        Map<String, Object> saved = repo.sentence(ctx.token(), req.de());
        if (saved != null) {
            return Map.of("de", saved.get("de"), "en", saved.getOrDefault("en", ""));
        }
        if (key == null || key.isBlank() || key.length() > 200) {
            return Map.of("needsKey", true); // nothing saved yet and no key to generate one — not an error
        }
        Map<String, String> s = ask(key, req);
        repo.saveSentence(ctx.token(), req.de(), s.get("de"), s.get("en"));
        return Map.of("de", s.get("de"), "en", s.get("en"));
    }

    @SuppressWarnings("unchecked")
    private Map<String, String> ask(String key, GenerateRequest req) {
        String label = CAT_LABEL.getOrDefault(req.cat(), String.valueOf(req.cat()));
        String prompt = "Write ONE short, natural German example sentence at CEFR A2 level (max 12 words) "
                + "that uses the German word \"" + req.de() + "\" (" + label + ", English meaning: \"" + req.en() + "\"). "
                + "Use simple everyday vocabulary and grammar. Then translate that exact sentence to English. "
                + "Return only JSON: {\"de\":\"<sentence>\",\"en\":\"<translation>\"}.";
        Map<String, Object> body = Map.of(
                "contents", List.of(Map.of("parts", List.of(Map.of("text", prompt)))),
                "generationConfig", Map.of("responseMimeType", "application/json", "temperature", 0.7));
        Map<String, Object> data;
        try {
            data = http.post()
                    .uri("https://generativelanguage.googleapis.com/v1beta/models/" + MODEL + ":generateContent?key={key}", key)
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(body)
                    .retrieve()
                    .body(Map.class);
        } catch (RestClientResponseException e) {
            String detail = "HTTP " + e.getStatusCode().value();
            try {
                Map<String, Object> err = json.readValue(e.getResponseBodyAsString(), Map.class);
                if (err.get("error") instanceof Map<?, ?> m && m.get("message") != null) {
                    detail = String.valueOf(m.get("message"));
                }
            } catch (JacksonException ignored) {
                // non-JSON error body
            }
            throw new ResponseStatusException(HttpStatus.BAD_GATEWAY, "Gemini: " + detail);
        } catch (ResourceAccessException e) {
            throw new ResponseStatusException(HttpStatus.BAD_GATEWAY, "Gemini: unreachable");
        }
        // thinking models can emit a thought part first — take the first part with text
        Map<String, Object> cand = data != null && data.get("candidates") instanceof List<?> l && !l.isEmpty()
                ? (Map<String, Object>) l.get(0) : null;
        List<Map<String, Object>> parts = cand != null && cand.get("content") instanceof Map<?, ?> c && c.get("parts") instanceof List<?> p
                ? (List<Map<String, Object>>) p : List.of();
        String text = parts.stream().map(x -> x.get("text")).filter(t -> t instanceof String s && !s.isBlank())
                .map(String::valueOf).findFirst().orElse(null);
        if (text == null) {
            Object reason = cand == null ? null : cand.get("finishReason");
            throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,
                    "Gemini: " + (reason != null && !"STOP".equals(reason) ? "no sentence (" + reason + ")" : "empty response"));
        }
        String de;
        String en;
        try {
            Map<String, Object> parsed = json.readValue(text, Map.class);
            de = parsed.get("de") == null ? null : String.valueOf(parsed.get("de")).trim();
            en = parsed.get("en") == null ? "" : String.valueOf(parsed.get("en")).trim();
        } catch (JacksonException notJson) {
            // the model ignored the JSON instruction — use the raw text as the sentence
            de = text.replaceAll("^```(?:json)?|```$", "").trim();
            en = "";
        }
        if (de == null || de.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.BAD_GATEWAY, "Gemini: unexpected response shape");
        }
        return Map.of("de", de, "en", en);
    }

    private static void requireWord(String w) {
        if (w == null || w.isBlank() || w.length() > 300) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "word is required");
        }
    }
}
